// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y96XIcN7Yg/CqIul+E7PiqihSpxWL/GbUWm27Z4ohUeyZaDhKViaqCmQVkA0iWqhWK",
	"uA8xbzJzI+bH3F/zAr5vNIFzACQyE1kLJVK0+vYPN1WZieXg4OzLh0EmF6UUTBg9OPow0NmcLSj8+VRr",
	"PhMsP6P60v47ZzpTvDRcisFR4ynhmlBi7F9UE27svxXLGL9iOZmsiJkz8otUl0yNB8NBqWTJlOEMZsnk",
	"YkFFDn9zwxbwx/+n2HRwNPiXvXpxe25le8/wg8HH4cCsSjY4GlCl6Mr++zc5sV+7n7VRXMzc7+el4lJx",
	"s4pe4MKwGVP+Dfw18bmgi/SD9WNqQ021cTsWfqf4pt0R1Zf9C6kqntsHU6kW1AyO8Idh+8WPw4Fif6+4",
	"Yvng6G/+JQsct5ewtmgLLShFIIlXNazP69cwr5z8xjJjF/j0ivKCTgr2o5ycMmPscjqYc8rFrGBE43Mi",
	"p4SSH+WE2NF0AkHmkmf4Z3OcX+ZMkBm/YmJICr7gBvDsihY8t/+tmCZG2t80I26QMXktihWptF0jWXIz",
	"Jwg0mNzOHVCwA/w2suVsSqvCdNd1NmfEPcR1ED2XS+EWQyrNFFnatefMMLXgAuafc+1BMsbhozHTU4Rf",
	"9oyUheGlm4iLeiKLj2pKMwaDspwbu3Uc0a1/SgvNhl3gmjlTdtG0KOSS2E/bCyV0auw7c0Z+kxMyp5pM",
	"GBNEV5MFN4blY/KLrIqc8EVZrEjOCoafFQVh77nGAam+1GQqFQ79m5wMCRW5JSByUfLCvsPN+J2oEX0i",
	"ZcGogB1d0aILn5OVmUtB2PtSMa25BOBPGLFvV9Sw3MJIqhw36M+BwU6aRxfWFc5m2EWNS7bqruE4Z8Lw",
	"KWfKDRJQfkgWlTZ2PZXgf68QEd2h/eYuQnIeezGomiXuwlOxIuy9UZRQNasWlsJ4fJuUq7H9UI9P5YKd",
	"4N1affMtyewxVJrl9s1MMWoYbtXdv1W0hvqK15RlBxTiiwXLOTWsWBHF7FCEwlZzNuWC2w+GlhDA9HbK",
	"IcBEVsatiCrDs6qgKpxDDz7oauLJ5zqqmyBUp+7LcNV3HuHMfX7FNXeXbMcR/mq/5IUlwG0qbnHMrWxL",
	"yntag6JFgKvJyD5BiCPOebCSZ5VSTJhiRaQlldSPC0gcEUs9Jhc/PD394cXz85fHr16cnzw9++ECBYGc",
	"K5YZqVakpGZO/n9y8W6w9y/wv3eDC0LLkomc5XiETFQLu78pL9i5fX8wHORc+T/hZ8e05lTPWX5ev/lr",
	"4o70nUuXhjoIRLuPLiZyCKrJ8XN/ZWDblnD8ubDrV2PysySCaUtOtFFVZirFNPkGOIQekpxndiqqONPf",
	"EqoY0VVZSmXaW3eLH1rh4fDAbrqQ1AyGgNfbbjJCnfhmBmQcprinkcAymhSOXLhvLo4ILZZ0peGlMbkA",
	"ug709OII0QO+dqTr7THycgCo4wCKfFPwS0aoBxqheT6S4tsxuViySWqYJZvUXAuwbkEFnTFL1IZkUhki",
	"pEEG6mZBtgR4PCYXc57nzC5QsCumYOg/tXHZkUa7UmQy9kUADgiwdnZBiyat8adVAxRnGgDRcXAZDAdL",
	"Ntl4ZmmM9EJQjScoPHNNfgIQKOSM3ABFpAvLtxISEzM0IXb9QPU8vvHAZchxhwRo4rhVQSesINmcihkb",
	"4jLsyGTJC//zmJzZn7lGPiJFffiB7TKhK2U5C0UBLQgHzUnt/ahKYMfUsAZ5r2EIS9pNRvcTbK1fpGTY",
	"jvjXIs6OQOHyojmHeBabCLZFhwRTf8W18RQKSG4/YnSRwIvv19v4WYMT9uy6niK1QXfhT6iZP5uz7PIN",
	"005cbsn3tNKJy/C8/peFwXK+8qKAmVuE+0ZI862j00lhiYuy6pHO4RFi5JJq1CEs5k25yHEWT+KTA+tz",
	"nDapkqDIM2dhoY6VSGXp1jgptAAzS64UBgkLncpK5Mk1aVmpbKPEER3JKX7QPlIEmltRGDbe89Ad2IYj",
	"f8lFXp/4VvjXgzAJ1au7D0v1YkGCai0zTg2SZLubcyaurqgaOMToFyC8faFzHu4BUcxqFSBiU6JRmXVa",
	"MdC79yyrDNtk9+g3KgTKHj32ME7TneiT1LG8UEqq7n6+Z4IpnhFmHxPFdCmFZikLTZ5A9R/Ozk4ImhGI",
	"fSOI72EgcmxZaVZUOepbeClWhaQ50RKxOgAQV9uArVUSYWlcoMGDSzF+J57ZyR7uHwauA6IAaG7U0AnV",
	"zD6ZVHpluRMjsFC/KMe8pDCUC0LJvTfMqNXoqdVj7+Grc0ZBL7TL4yLnGTVMO013OefZnBi+QFXRHgXT",
	"hmRUWKFRMaO4VXpfSqsye7HEDcg1CC4WTagVjj0vv6cd37PvZgVnwgAXlETLBbOK4YwoRrUUQEdAnGLv",
	"8fJwWpAJzS7ldIocM1iGvCjZNUstmNZ0lsK9FnLBudfvpzDrZUEXTGTyr0xpZ6hg7+miRNqIKD7477JS",
	"nk9ZmjKXylz5DwaH4/3RhBl6fzAcJH4dPXw0mj14/Og+O8wfj3KuzMprwlvcpeZciRf6n7WA4V9sjekE",
	"jxRsfkRjJC2K19PB0d/W075TLxTZrz4O2zySZoZfBdF+DZtEuU0b4r+wMpm3qyQ5Byr+KXJnH4AMxxdM",
	"G7ooY/yyQtrIPkmNCYYedu6uB8vPaYIRH0+dBaBgMI1lcOELJ29yDTsKKyCWEeIdtNfT3z/7qTZSoQjq",
	"kTLIRs2bsXblPAGIt2+Pn3vY/ghG1A32121Nv1bADJbfqszT53AWNi+neLb46njLTbU5vF2wP/R62sgk",
	"HJDt14+/Ih7/uZDZZcG16ZdRl8DmtKPqigGtA8shy0nGFNBb8BCgJCst9dUly/iUZx45txIT4vW8EEat",
	"UhJC96WO3Lne1I77Od/K3h7e7qFDrROoh44t6z0k5Lm7HsdiKhN3SEwloRNZ2Wth74blbhOGl6pmjXj9",
	"7W1yD7pMXs/pgorzzApeMiU3x6LtKbxM/MuRwccvQLGFvGI5oYUUMzS0ew09IQG3ANReSw9oXlFt3oAg",
	"yPLjBZ2xNIxeCFnN5rEQAUYFGvHakrOMESNnuMWcT6dM2Wd4gmBKtV8TSuZSm5FiBTX8ipG3b155zm1v",
	"5ki55RBu1zMmZ9LKGmgcQhvJm1dD+5MVKgQ1jLwbfLAiy8e9D1IEg5yuplP+numP7wZIvJpnZT9ooqUq",
	"klTIDdOQwDf4NVpHAVNFI/UcxU/MUCt9Aa/KczDo0uKked+6XKJhwVYTbhRVK7Jwg3noj8lPUoGIXRbs",
	"fWxqc3LXQlq0Bp24suIkuaDjyTi7sDSoPnAL2EsGRu1IRimVhH0cDU5LxQ0jLxWfza0KVGmmxmxBeWFX",
	"vZooJv7LxKmFUs38G07IOYUXyKn5v//nihURXBtwOnHutWdgPenSpNihuKDv+cKqNPf394eDBRf4r/2u",
	"TNc6szBIz2GdRhaR9GEZVbGebwNj8+oWcAtUC0VmjwF9hCXQGfjb4T+XYjSlHN8If5RWmbR//L1iFfxB",
	"VTbnV9GfaBvF4UdBQhjgplnF8HllD2YUz5bU7sIe+o4ARe20No7PIp+QU3/QFvZZBIE2KfRM2S2r70iN",
	"VL0E0D0EChgstEMnRwVhyd6lSoNpFIm3fQspHcuJVao1shPBMqsRqFWKNLVI93lKnrr3zPON4+f3IhUO",
	"hBKvNLVZTOwfHJOnPLe6Ja7Uf5JiR141dOzPs6Wpkouw9aStsecCn1F9qU+rxYKqVcqzvSgLPuUsJ4WT",
	"i9C76aE+Js9Q9UT1Fh7WNm37kz8kRq2QS/Vll1XDV1tbVSC+wC14C4NeL4nX/7ViuOeIeoLbfXD00GqJ",
	"NQfoo6kfhwPwuZ5PVhCXgKLnObg6HKL/6v8656JBXQJ5cJTj144S6NbyoSaV99Pq7yezqpe8MExZduMH",
	"G3rG8+r4Ly9qvpN0oMrpVLPmQvdTC61B9WGHqAS9JXHv21Fsk99lV9GptW/FG2YqJdAFYzEMxUHqqSd3",
	"EipsYRctIIqaaSN1PwL3WaEB9be9U6ikX/MuOa30mRRTPqsU9REezfVw/ZIrbd5UYp0ojiqyZXoc5U5L",
	"66b2w9pI5eYjqhK69teEmAcQmyiZsiWZUks19ZA4l52QYgRhGlYUzuL1Aj8gUgXNLrhxJpYdE7YojaW+",
	"9i0zZ+Dgq4pc3DNkwnpd90DyX4CZK99KAYFVGEWFnjJFnp4cg//ZuzHStnaN3PCVzGg6tuZ54B7Amizj",
	"sZcC5nIfjzdq2e1Z2rsbxge8Bkv+ShX3roY2gpybpVzSBBt6LdhoSVfkyn2MzjULt4XUBmzV0t5HhiZI",
	"8ExbzmUFnLKgGbhakUdefLDy7ccLp+VwhWExXnqYgy/fCQaU+FjA4FCh3vxNzpYysSZaaOknzTs+3SCo",
	"MLf8sqDGKj2jYDjAIB3g7G6QySosug/R4KPNerozrteA9l9ucV5Pq5wz0XRMOBOJUxx0UjxtDaPXcal1",
	"FKqNPh0e9hMtSwtjOGV/KMRuGeJ1TIgC4hiTl9jw6i+MlW8qIZJRfsfBdL6MLi7CgCzoilwyVlqiJLz8",
	"lpZ2Fp15ugday+w9AjgK+2+C7rBmtd4tEYv2tV0yaJJLh9fHxtE2FJ7njFzgI8ud2AWxW3Fm1DjQDK+P",
	"nQTgPZP2v4K9N84jj0T6wvLqiyG5aALhgvz09vTMar4XEHjVg+gtdG4BMkCtD0YpLA++uWPvXG3pr86R",
	"uf5itVxvieFv3Vf8xVy6oLSwfDNHcR7Z7Ryxb9jMsm3FcqS/XUjSPFdM6x3jnR39Td80OTVLqtiaa7iJ",
	"av0Sbg7KdSHc4TzYSfVu4vAnRUw7BuBBFUdNe0AMBxnGy8EKBxEUelafOq1TllWKm1Xw07Yo4LYOu3We",
	"ulNmqvKp1lwbKgwKnykXdyzkyYmV7by6DHKXHYWEYbrU2hnIXoAPnG4RBNnv9P9Sglp3C0l4gjj3rNdc",
	"fspA/Xd2E2f/5oqc/vD04OEjvPa6WgyJ5v+AoMLJyjCNAlnOtF0eKdyivPO8a+BoGTNhNvA1IvkZ1OG1",
	"45lEIXRwNDh8ONl/8OR+dvB4sn94eJjfn04ePJxm+4+/e0LvH2R0/9Hkfv7owX5+8PDRk8ff7U++23+c",
	"s4f7D/LH+wdP2L4diP+DDY7uPzh4AM5KnK2QsxkXs3iqR4eTxwfZo8PJkwcHD6b5/cPJk8PH+9PJo/39",
	"R0/2v9vPDun9h4/vP86mhzR/8ODg0eHDyf3vHmeP6HdPHu4/flJPdfD4Y1fn9xA5SVJb+2skPXpFyPHr",
	"OOLZjwP8HKRJZ+B3xv22NQpoONVBKULHYzTJmBwLIoucKeJcxdob991YMK/lAL9VGn0D78J2yPHzdwO0",
	"C3nt2I1CeIg2oLgK0NUunMllpItqtqczJtjIUq89DDAfHT+/6ImocyizpeKLa3/JC3ZasmyjDoyDD5vH",
	"tPk21dw/ZYK1z9Cg1jqVVOrINdDD+UbbiAGKswN97SAycyqc663pvqa6MSj4xVwkJPVh//U1JmeRdPHp",
	"yNdj0GwEd2x3JOGouwTOqWDUS10UKa+jVW7RER1OS4otb7Ksx0NTRj1icAemzOxzmlhhk9TGYybHADrz",
	"oWsZY00aPdjogLGrceMN+4XdJoB/4WZeO1e2ArVXwjMgZ5Me0A+dmDokOSuZyCHlSoCGh+LMV34228qe",
	"0XH0uGI6pxpbrdcdb8dnVolLIZcCwi8KSXPUxzCCJWkWwMHe4Gogu8fpadcWPEDQaMCuV5a4IaHhVgSE",
	"W2Bv/YffPC8MQExzNTwtELMpUdFnnqUM46N0tgnZvO5MXVm54yUMFcJwANEsJ3Gv2d/YexeUGeT6OPjz",
	"tnCgvpjhPtwMWsQThev2mXElIt+fijWYHtskHG2HLp7/rjz3cxHCtURPsfx0k+bWZiUaPqs5Fs2tUOx0",
	"uihMjDqrKnlX7e8fPAr2YCedVdpifsfQbKQbMDEXClPhHjgB6p5uujtSnm4aWXh3sMQGw/DH4aCIALSj",
	"reUWXCWtUy9qDTlsvWEIaa4piR0yu2Tm+PWPcvIWfL/J1ETNTMgJHxJtpWx5xRTxX3tnAyRvgc1Sj8lL",
	"K+SwJfgXh1YdYldcVvoccfUixKV50pc60X/6qFVv92sO9DNdxJmi6bzkBrh38t3GIU8ha/Fh0iOu2FQx",
	"PT8PARBrbfhROL3T+N33GHqBu7mnMQijdowCwmHWodYu1FZ7JxT8ExycNJtDdsAVzyuKkRxkCbPMmGAK",
	"7fqSLKhY+UFcDnqpaGZ4RoteP+juQOyvGLFrVPHWOLek+txFk/aUZsArGkwc7uX6jtiLbqRzcjT8Ho7g",
	"25chasAe1j2e3yNTzorcfTv0kksd9gpu562cIbwn9tkVuYjKYDSRbh1Zi+NR++ibw1GpahxNBI6GXBoP",
	"QLfSdJbfljHKZl4tJgLCGTdiVjq0NpX/V0cx419hknWQslS+v7jFKRPgxg0EH2+xJlSTiz0dfXtB2BVY",
	"YaBigJEuU9iLydGb9qEFpruKY/LMj4kJzjNm4udoewNfn73Y/gL7fxdypjGuQTDmkr7KgmfcFCs/7YQh",
	"VwLPun20GoaNZNSFw4R37RhSYJzaN0bCehpTTz3K/CYn34LyZl+3r9zTdj0EvJb2sqZYmyw3Sn2Jo3nt",
	"fZfb1kRIDeIzSb0npp9LYaqTkU2o7JFK1D9YSW28mZe1EFWW60onrN96pLaHZUC4af2vpMbeB4oEraSG",
	"XHJ7otOdYBAicIviRzmBzI2i+CUEGTheTfVlIWf4ML7Wa1d9RvXlKznro2Jn7hKQbF6JSyekQbhHuLNK",
	"ygXJGXLkHB+6VD+7JLit9Ery3H6c46ab7DKFx3YnXaeVXURAIre0MfmJrkKi36IqDC8he04wtMSz9ybp",
	"Cva0bC2qnqGzbzcsrKmk3cY6TLTDbyMhnwEk+0VkAEZHRnZRp9cTkuNMtJ3l0O3ANtyFq22WWZ1j9lOF",
	"1madrut8c1OyWEq0CazZ+bDXpnmtwUQkJ9vgIr65Dhtd7I/Hx14NLK14efkc+SYzdWy3G9fKSVF60+fR",
	"nFz4xBY4a8/tXDOWMnfQOh6T63i99n2fKB5Vcthu7ZtRf+lX/6nI3wnM+ISvzrOQebHtx43QpJtVa7ZO",
	"CN5wu/w4ycsVJ/smq8DUfvuoXIqRdcpC0067TfD9pyc0uQeHv/8P8h//+vu//f7vv/+v3//tP/719//9",
	"+7///j9jpQnU9zgQ3c1yni3ywdHgg/vnR/AMV+LyHE21h3ZPxmrH57TKufSh6lNeMBdhsId60p6e7v0m",
	"Jxo93fcPDscwZHzIJz9/b/9Z6sHRwYPhYKrowtKYwf3R/f3BcABqlj6X6vyK50wOjtwvg+FAVqasDFaZ",
	"Yu8NEy4lfVy6qDnYinuruy6cKaxsLw0uVw6rM56S0qwdz9U4w+JK57WRcFBwUb2PMBoCekcO1E6/7GbO",
	"x5izQScMOX7bVsTcYM2JEWSTocO/WocFbWUeqZOieqDWiZxGsV/MiF5pwxZ1Qqb7tlXwCJKlMjkTXLOu",
	"5dm97KxPELJRyCVTo4xqFiI63BR+US76/h0e6LvBkLwbLLnI5VLjP3Kqllzg37JkYqJz+w9msjE5DVPJ",
	"RUkND1Uuv5f3NLlQlQAN8fvXr08v/kRUJcgFhJ7KguRcG8haglhvq3/SkMRUSg01r8IiLfd+qr1pnhbE",
	"7mjY2Ad5N0BtXL0b+LgJV6wTbaFe2oRqW6WCfGWqybtB0xDvx3s3qGG/kNpq2qDwXzJimDZ7OZtUM1fE",
	"SxNGNYdyWU5P99ltGNjLM5LLDMokQiJ6UTR2llQL+ixs9ofz7StuDUkmSx773i7adZfGdrSLUIWxW7Pr",
	"zP2rTra2FJ/lhDuzEZrJcsm0uGfIgpoM069pZipahJE6MUtnWP0RjCq6XcoL8EgWeZQe1Cz/2a6kFsqB",
	"euvVO3HcWKCV5hbI3IZ1GAFUb1mVVGuvgfSl22dFpQ1LVLZB2YE8w+doN3G30FfnqXMJna3SDUaOn4cM",
	"Bmd9dCo1etmoCW968FuSk1cFkgO7NIyvAIsmJsJIFW3UYpuvlmDR0n8RVtQ0/G+lWjo5pGu9TBC9lESS",
	"LvF85vVpLOoMqUDaOxt9ZJMvujMkfMzGZMKmUrE6oyDKKBnvpkx+zsLQN1HkBBMRzyerc5/YsUtKplMs",
	"EmvdUvHdQUcG1cTIyuLpBpEZVTWxCkqK/b88oKdP0dhNQfnydbNvqraKJ0W7nPi29VjaKnyqZHdcmDtc",
	"pg01up1tb2NBEfBNSFefOzLdfZITIh3IZQkNxCK1jHjDRnBSF1MiW93GmStVpCd+++ZV7KCtZyfcaFZM",
	"Q9CnXIpC0nybZI3a1BdOEWt0wP77TmX34gqhjEJIj9Zyakbt6gopU2894V2qhBDf6muUQoiT3buKdaUN",
	"Yd1qMDW6Y30i2ShHWzuJQRzuYv+Ohsq7RAyva13ckiL5mfpOap17AZ8FhzzkKDuxzkhHpVE1Q8xzEUHg",
	"mQOKBScG1fVQ5IPKxk+tpB9OD4LhZIm5lX8i0tlZWi/wmYAYjW9AvpE+OfXC01tnNxfSEKaoSwIM5dfa",
	"Urxd1rebDOvddN6CC1dJ3QU5QND5PU2yUK4bc3F5XG4JyDV5fcXUUnHDULbnstJgQhVRlThfaicpPqSc",
	"Lq/kzDlTAg1Av46Xin2Vb7toOBWYkFFV8J66qqZBAnegEknkqhPfkrqBYhDBnzHQEUGZ5wITmHGcRFz0",
	"upy5T6MCay6ZnzR1ieo9bldl0NlUQzWQTnolajaJ2BqnSmmUEZFTcu1vJFR9X7DFBE92KyEYP3XjJuXg",
	"8jwCeEtMOSHuWcdQvzaQbjtrT/9Yn56QaJymtRk0oJNtRX4jSDUi8qKalclUxI+/dopwuQo0TdboKW+N",
	"cs/6NG+vctcVAcfkKVoHqAi01pIfCPFZ+RQG9xk3kbUMCroAARkHHdzJYiVVYJgKfl2PuURz+xsVDKic",
	"q9xeW8q7220ULrTD55J8f/KWoMU0kNMXL/764gUgdz44Gjw4vH+QP/ouGzH6KB89ePjo0ejJZPpoxJ5M",
	"959M2IPvMhaa7RwNvj95O4Lvu/bXVpeX2yIr/cTEHWDT45Io6YIhjEb6DPnGOeoOdXDNouxZNg/EfXHO",
	"raL/t+0Am8gDjEeJruPmoKh1kdrxqBsh9sqVx+ynqJ+DLH7sXcarbcpzdnnarraLNgtZD0E/ej/0MFM9",
	"irXplA92v4yCMzPh9NAsUwwEWTkS0owMK4oRFSspWJyTfTQ4HB/0kcOjv3k/lVWspouSzVz/kVHdgGIw",
	"HCy4zhIoeM2kebfwD5+f17TVJ5ypGbKdmmIjiTjlM/G657CenhxD36kI6ud1VWe9pLMZU6OK3/YhdBdz",
	"8xD3bDoN5M6K1gC8YKw8dVbmRBSGfRys0D5nAg02vvzOqbEck4qcMJFjLELQJHyseig7l9NV0yISxrak",
	"HEwSY/K0LAvOXDwGxmJI+yEHC/FFTlf6XE7Pl4xdXkAOIrzT/N2+7GN2EysE7UuQgwejuawU+eGHo59+",
	"qquQdVh7NPLgaLCQxFQEkjsgVi4/B/32aHD/u6P9fayk4cwrzs+s7Qr8W/tP7Ftdft2YpJuoSTM20qyk",
	"CqPelnJUMGiD4yvJOqhbucKOBbSZscseMJNv3g0WEn19pvJuvm/H5AX4FRaMCk3eDdgVUys7nq8X20HU",
	"ev8RUwSA9pRD8aD5kA5QD4DaPFxbCAljD5vQbIwbrXjNvTDUsD7rlQs2UXHNn+2DVZK2p2iwrRaVt2hk",
	"SEOjS3rJush1naia7XOzGt/FUa0W6piBiusaDqi2JMUeAlQkGQ4M0+4VOZ1atT9pUuwP2ekVIJFY1YYd",
	"J03W2cmQIeACFBO2N31e0H+s1mdANUs5Of0CrSVxYzogUrVHE8WN2sLiDEqaTLnget7yTe6cvrHNKQ7D",
	"/tacZ5+1889U82yNMndtQ+aXC3T7XFWFPlsYWiRMNAHx1zq2I+R1tVQiFepwXcPgullm8B7d7QxDzSKx",
	"H67r30nnhyTsDGfoVQ5KYYSVH1EqhoJIVuZZxHrKOa1SpQneaqagdJ3LvHOId/x8SEqq9VKq3D9CMdhV",
	"KLRCjjcH1mqIRUwADFxse43qnc6NKQcfP0J7KfSfQYh5ZiIZOJz4GaML5/nBL/XR3t7Uh/Bxudcty4fR",
	"+eQlVQuXzALJmoPhoOAZc/njwazw6uqwM/5yuRzPRDWWarbnvtF7s7IYHY73x0yM52aB5cm5KRqrXYQO",
	"LbXAfn+8PwYpSJZM0JJjZ5bxvquAACezR0u+d3W4l7ULms5QsQkV8I5zaDpkmpVPLcpg8jmMdrC/76Fq",
	"JX2LwVbQxNzTvd+cQwrxdsvU2+Z8cHhNoAuL1UVIgkcU9HTVrhiDU5q1saad/muGzjSW4TIUdJN6jBci",
	"LyV3iYUz1zy3M2AnBdRCPgnePYiU2fOqUh+wX3KR/zmUszrBmhU3Bu50968EvF/KStTVrUAGDv3Wmo2V",
	"P8u6sKxaYh2nob/S0jL4pZLQe7lxci+5S7WSiiykYuTZq2Pf7Qt9HxBWpsmSQkAaSFN+OymkKKVOnBSU",
	"PkocFbCaP8t89dmg0SrhmACL73MmlXOdQSAPli2UGKOF2bg3j0eNknDdlf7cvLhDXCRGkcGRTrlgdw+n",
	"/koLDv5LGmPTdZCphafOCXpVj++7rtYHuZGoYIGEURRnuwZlGwUfvijWntwafv5TICbWxagxslk2YwO7",
	"22GcXmSEUlDbShEvsW7UJx35Dq1QPg4bY63oomiO1ZaLNyFI+yDeQCfBK5YWPLpywtrTeJplTId28Kk6",
	"7okhQ6y1kIbgxu6Bi/x1ycTTk2OfIV0UcomS9YVvm7znJEl3oBekpNmlPex3ov+4NTNVOaK+smg/2Tml",
	"VyxZzPRmCE9yqiTTjMFqaTe9QvRuIeWDRMpWCxkgwHvJJrQsvbkityrStCqKuoiFb41v5cq7R0re1hE6",
	"PUV1sNapYsjkOJS6tDtckWklsHN6Aa2dNqC3RYgUZvfWrO3HwQbn2/vg69x83PvgnSYf15GkBjNstmW1",
	"Cji3sHOF45wKF1XSqRVnZ43eRcXpVheyWnxiwsj50z9hm3r9eoPMNF0xaneK6bW0VnmnolFpqtFIPa4x",
	"Zb90JgFfYsoiZ6gvhaa+HfW7dctpNCDqLTvVj6ohx2h3LK17C/wnhl5jA/oTkLOuSdY2H5C32jd1Z0Fo",
	"p3k+QmayJskMyWhoS8AmmFA1pdDR0DKOVC4GmVBd142dKLnUjWyr62N8vcfdcdw34enh/JDLgrWsboTV",
	"N3rwdg/5RzlxlTkW3HTQ8yY1jjULAuN6ZSU85J0uCcuKai5aNKpQpQHaD+4f3LyMcBYoasg2Y4bOICnN",
	"9cH2WWnNF5I5aVxDVmSxInnFWr2yM5rNPfKFoeA+SEkKK5qg3Hlr4hE8IL4Yf5MSII4R6ovVwULbdyTq",
	"Ih/LPthRqjHcj80UPeYuZedSoWq/xdUCvfbL3q8sWsK66/UgnTq/44UIyZTQvR+a9c2tQPnz6zNMXnQV",
	"+nizxfyQmLmsZvP/vFB/lAsFaLXhOgH2h33bkcCUBrW7ltyeuKm7VPLENWvUcus3yzOTzb8v5IQ2KjJB",
	"RtbNcpG+um5bCDTD9JU782XqfLYx3B4qVsmGyD1yEbRRhiRdpq6Y7iuLpzcc32voV4ItNOuknhkAumc5",
	"rfP7u+9xmSaT0EHQ1dq6CQpZt9lMad3tKvAYnwUdFTFjf3zbQkmjpWI/FgFUI2OoC+LG3GioMcCnloQB",
	"1QEy5joZwofjO0Nr4N6GoggW8NshZN30cgp9NqG3nciJlhB400VDS3H3Ptj//kwXbK0252oGbKXL+QHv",
	"jGrVrnzQKxXgszbpcDGOgUdZmELnugCJDecTZbtGVaZDoYXkuegtTkMPbhFoSYU0vBR2oxMAjFAZ30Ep",
	"CKpnbg3EeqrAdsN4XRB+wKCQj3W5ry4gn8PvqOhtxuqQYduP05vCVn7dRrh8jiQoomOhCHSodGEUn80s",
	"g7ldovVWsPcllgCBiL2uOwGj7cKCfa2JIeEiK6oc5RlXCxmbgloOLmfYmQClZFc9JAyyoKsQRufsCDS7",
	"nClZiXxMfpahG5cOSYGuPhv5ZsXMt00bQ8CsfpHpi2LErWjz3JfZbTOdlkzzm5xsoRniRyInUeh8333c",
	"mxQyuyxCEkn6Zr6B/uk/ysmfw9u3eSA3InHVW0lpXVVp8febpatuiBniq5J966p5NzrKwx3ww23p/PF3",
	"k2YZK6FADBNGceb0UCArbpK7RlTsosJqXfMSe+cjEOx6v78MXt3cRV+LXKD+rEEwqxHNpEF4RlVY4Pbf",
	"JVRAGgVaWzPfrO5D4/cAaJJLiH9zvcPDlnVzh+ulDnRqB1SLS6b3Sx27KOhtdRm1868BKf/gVoDmUV/D",
	"IpAcNJQxWI9Ampm4YEePORU0gZO6KsYfnEX6nbhcmx7rpGBL4mEzvp4B108UsoqpDowRTa0HB30FaXyH",
	"br8EH7yC34fQty9MNNcga5AE6i04MDRd1BsRtE6LWIeep6F6yx8bORtFjHpQs5kCBA5VWMs10fS0Mdx1",
	"kLS5IIepYGwOh+3zjnTo9hUk/z8IGjc3uQsShw4/a9nzGbz1dfBk2EtIwUnLighjznRcTEh3JJ87JhZS",
	"t24ogQStl+pVN7BhG3kvveM0Ei3n1IygJ9MI9dlRLntxKticfplT84v96Ng8/1oEvufOZNMn5/0YdzRL",
	"2CAs8kUyFPY79mVavE0H8rtxFHAe+vqq3sGK1fSGYGcq5MwFrvTKY2Ayct156lnq4dCwBBW8RLEKq8ik",
	"8GG8xcpPwTUJp+29D75+M7ZQRsFTVqbHKPV5YBHjKrbL2/Odc/ewBOQapt1sOH9DLvrmJCkvVNxe1rtV",
	"ieu+fXvOp2TD8FRYrm+abZm07+wdhQcgv95/cvPEMqyEForRfOXK6TqB4cGtBBAoRpb2P3h6EDUiZhB7",
	"Ri50C6J1D9qL6JogyvNsTqRw5v1bYzdVi920iNQz7OdP67bqeP31alFwcem6xSGCOghgSIhBouKAUlnR",
	"pSgi6xs2jUVq4bppuirHGS2KcMHr4JuafiBQ2wHLbkGU6PgywWLiZtqWuNG1NCPuFLwt5YhP9kapSKpb",
	"9bYE5QvQkmSz5tR6Q88bqHYvQZyPD2IY1/iw77juxs6VcqeuDDQDJ9SjdQwD12IeY/RLqYx2F79mvG5j",
	"GxH+KSaJUB9gFNhGe8DQj9YHLWFTa1xFTXbgXW2sgBCW0L0lMOzeB9/w/OPeB/iF/2ONQz3ufSwV89Fw",
	"LRlw61b2UC+uKzD6V3fyww8780YFk30X6FArOTGr3/02s4YCtDcd+5/qd72lIfJOXaK40EjdlzvZob0h",
	"YEb3ZR3xDhj5z42Mw5RRxREV3uz+y10xRzZlioS27777ROGSrN4NDva/ezcIiFWX8gWlAvx7plLCi/T1",
	"9nSQ4zDMNPTZ7xw4ZsrRQkscQ8sFk4IRVmgYp67gm1omYAsAcM4oZgE7EP63EU4zekbF6Lnd5+gtDDBI",
	"wDDqg5uCoVR8xgUtYE47PjSvwBLBhYxLCjt5wapxUQcX7BfowwBw307Jc4UhqSCUwxvQqGXGMYx0095e",
	"u4WNXrqFDTbGKm0jz8jMMDPSRjG6aFKIoKlPuLD3e7g5l/MZzqFj/L+eXdGLoV2T4sH+d5ted+jYQERH",
	"cjBI+XFyBOU+t+oAhhBPmFkyh+y+V3lNdILW7sJBYAFYvF916E4QnT0ug7LzMFU3Nm7UveHW+htY3xyH",
	"eKWSmasJPGH2wzD/ZNW4dyhRXPReoSMCTald6SKgLjE4bjsAegMHAs7gQqD7+Q75WRpWt51uPIT7OZUq",
	"45NiRbJCujLmP5ydnZBMCsEy7HaP7UEk1NZyhNfVw9KN82KEvaeZIZoumJMkjfSthUguKyvk4Qd6/E74",
	"U8XsILxNdSHgxAmQicxXvaw0TkO1U9TaRRcsseQI1sW9D657w8f1BmjXzHSLsMvQDOJuGghdoemk4wSL",
	"nompvKOW5WZbkjVmu8QXa05+z9W8X3/6vovK14IEfj/rcAH6onh86AloaktM8OGcaiKgFQBZMXO30CmO",
	"QOi0oMFI7QXD8j+49w0OMFe8oRV2EFpTb0A843r0b0S+M/vi3UE+w96bvbKgXOxYDOOsDZyvBa+iuCiq",
	"DZmyZdSAfB6379+KesWfhPF8H461WLVdUEDUVuNWserzWyA7zY2++rgAZIFfQWAA9qyBgDIMML9ihE2n",
	"LDNerIW+lDgC1WTJisK97y3w0CKUUZecPq8WVGiMgQbhFFzIV5x2E+brPhP2jkDpWX+jMKARLlZ9ry4I",
	"F9owmrdK20R1QXurMITeHDfG0n06hp/q2pUPQ15Ho2VtXb1gfaUAVO10aMGKvYK8Cdi4bFTUJosVofV0",
	"CQkdj2G0mJk911ph70PdpmGLrJJmf4VtlXLfnyQketzliOy49q5buLsglcCaq7rRhDSErvtdos3fjqUh",
	"y7U+3hr8G0K5N4D58yF5q19Gmsy3gJFA86AYtF/t3ftm/ljj5aeyyLJKwBkrLHUB/fm56VYwds3eEgC8",
	"piHMY6Pr9RauHibk352sUFfpigr06ENZrG2RqIGEQ7dVKESOVIzQLu6uI4YbYuYaB6lv7Vq+6sl/+KWx",
	"NT1ek6G4bL/afy/TxSohOODOXJbPfkmi8Ja7czNCRIZgy+vcCRQvumefvgJRJ6NNN+AWUL8P5/8C5nm/",
	"1k0Ir7eCk8ty8J96GbbhCUiVlO4Cb++Dq7O+gyy1la4Yhr35PN1O7VWHP4GBuCC9uym6eTVo6Rr3HIM2",
	"o1gmF4vQTxOckxnE0oJnxNVLrC0jy9BmgAty4Xp2XIDWhK695ksYS+E6Egwthy0JN2TKlTZj8lSs0NSC",
	"r8Vl+6NhvDMQaGoV2mNcT3D8ojj1uUnBGta3bb7vMrTs2EaQIDkz0AE6HLE32G538/c0M7FA0Wsw6sgT",
	"t3poN8y7W90+0ozc01zPh4+f64b+VTuxfINUIqc3Y126I4afXsSMKsJ6aCFE9JyXwaQQ2oDsgqybbJvu",
	"ELu9XL4WlE32p7kLJs+7jpTb2SSXuyNlwVg50lHPvk0sr9nk72vif82dbVMtH0JXGl0N16Ues1jCEzL1",
	"5d1Eww189YtixI1Rqk3I4DOJ26d4bRU5dFX8ohaka9InK83JYANr9KVLoHnLWYFNrZjyrXPX8Ed8MQjf",
	"N3f+jX6//YIx8CVc1K3mAnhIsLxfdu84Te5OJJhffsPm0tEaOjywPhIrh9Vf6gRSWeVvJKfTNYoBn4nX",
	"0+lWzpW7B0vXeg5IbKPp3N+gj11snVKXsQJMNfHNMTcA/BktCoxJ9KYaI0nhnG2+ZOmlkEv7w+qeYmQG",
	"BVPc8OPeUxEbDkXc6NV2U/Rf6gUzNKeG3uqN7raK/UNc6a3R8Gll5kwYbOXsGkBZbPABk32mg0/GSQw3",
	"NhJmcJm2MuJUvD7wJMYal+6aFIyjUxt8aeSAlXrFoG4B3CeQCkn6v7jbWLU7hvg8rtBtV2FuhFj1AKEX",
	"FUZZ3TM5TcIS/ZVvWqcOE6W0ltqpoQOe7iyh/oEpj3ffIYi8cRkCDbJg9dKEZpZsFCzHCoSYHuUoyqgZ",
	"+eTRBTygXNRpOY7KMDUqZEYLIHC00J+bql2xxm6qlK8JQoDW8Fknj7vo8JurAuus8L3B21BULeoj0Eeu",
	"fpa+6mdIvgylsCJj3IP9w8/YUwtRrBcxT5jyLQ2eM8GRdLos/bQdHQPlHMtzvfMBo4ZEy1AJqijkEh0X",
	"Dixu64rP5oYIuXRheoe3y2D8RaICMs/Qm2elcFgd5o9BXvpMQq9kl3+BF27HS+t8hTSMH0Fj020CnPIK",
	"p0p3m0jGyfVfFzskGoa/hpBTt5O+6+hko6gn+/WtGm6sboxp6pbUmRy62XXbYZIvPqmly9oKY9cF1G7b",
	"YPKJzCnyNtidD4lZlTyDCEPXBgQE5lLJmWJaD6FPCFbAAe4zpbyoFNvIYTxf0UzkDa+dBbcfHWpEM8U2",
	"35S9BV2N+EhV/cGjP9GVM6VU4qtIPfmJrv7CWPnGNcT/utQzDO92YkydoxxJzJEfPmJQqhJkj1wyVnq/",
	"fB3mTV6XvsIRpMtRLjShBP3usUwa/BkpZ3wPInckelD2opW11sR1HXu+HrVlZcrKjEol8ypbJ+hbYvka",
	"Xj7x794J5gCVqfZ+K9ls15zhofu2FLMvlW58sGW6MUh/LpHWN6d4cP/+zV+0V0zMzDyU6PlT3JIo5zk2",
	"orVUlhIHgpH7BLPH3UoPb36lJ3QFWaXQD4kq10jmwf2Ht+FG0FVZSmUP6ieWc0rOVqXzmAGKEcQoL0xO",
	"QlJ03V4wDgV7cPDkdlpX+SoNyCmBdEhJFlSsyNRebFcOzsVLmLmSxhTMFY37Q0kemI1tAb2Q2hDFMsxR",
	"DwXuYL8oD0Q52RyAU5U+rKp2hDChsUIdZkqA9O5O2X55T5Ocz5jGNv2tMybPQo48BI2d/Pw9wPnHkxff",
	"E4dKdtCyoEKkg7bWCTxmXi0mgvJC75WKXXG29GSJKyzr56k9QervxSCAqLry1LxSxeBosDeIjFBtYnXc",
	"jIjqtPjymBLYAaSidMtd/Cgn3kwKMtrfK6a4Rb+6j96w1TRh3Kj1qBODPj05bjYei01kcrGoBIqbUEYj",
	"1b674cBNTOCw4aewJgI9uHvbfmLLJbsNe1eULPyKOpOB0zFR0AWT5MMswCfqDH8HwdAM7Tc5CXXL4jlc",
	"Uv7HXz/+vwAAAP//Y09tqWkAAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
