/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FlamencoVersion model module.
 * @module model/FlamencoVersion
 * @version 0.0.0
 */
class FlamencoVersion {
    /**
     * Constructs a new <code>FlamencoVersion</code>.
     * @alias module:model/FlamencoVersion
     * @param version {String} Version of this Manager, meant for human consumption. For release builds it is the same as `shortversion`, for other builds it also includes the `git` version info. 
     * @param shortversion {String} 
     * @param name {String} 
     * @param git {String} 
     */
    constructor(version, shortversion, name, git) { 
        
        FlamencoVersion.initialize(this, version, shortversion, name, git);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, version, shortversion, name, git) { 
        obj['version'] = version;
        obj['shortversion'] = shortversion;
        obj['name'] = name;
        obj['git'] = git;
    }

    /**
     * Constructs a <code>FlamencoVersion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FlamencoVersion} obj Optional instance to populate.
     * @return {module:model/FlamencoVersion} The populated <code>FlamencoVersion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FlamencoVersion();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('shortversion')) {
                obj['shortversion'] = ApiClient.convertToType(data['shortversion'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('git')) {
                obj['git'] = ApiClient.convertToType(data['git'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Version of this Manager, meant for human consumption. For release builds it is the same as `shortversion`, for other builds it also includes the `git` version info. 
 * @member {String} version
 */
FlamencoVersion.prototype['version'] = undefined;

/**
 * @member {String} shortversion
 */
FlamencoVersion.prototype['shortversion'] = undefined;

/**
 * @member {String} name
 */
FlamencoVersion.prototype['name'] = undefined;

/**
 * @member {String} git
 */
FlamencoVersion.prototype['git'] = undefined;






export default FlamencoVersion;

