/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobDeletionInfo model module.
 * @module model/JobDeletionInfo
 * @version 0.0.0
 */
class JobDeletionInfo {
    /**
     * Constructs a new <code>JobDeletionInfo</code>.
     * Info about what will be deleted when this job is deleted.
     * @alias module:model/JobDeletionInfo
     * @param shamanCheckout {Boolean} Whether the Shaman checkout directory will be removed along with the job.
     */
    constructor(shamanCheckout) { 
        
        JobDeletionInfo.initialize(this, shamanCheckout);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, shamanCheckout) { 
        obj['shaman_checkout'] = shamanCheckout;
    }

    /**
     * Constructs a <code>JobDeletionInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobDeletionInfo} obj Optional instance to populate.
     * @return {module:model/JobDeletionInfo} The populated <code>JobDeletionInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobDeletionInfo();

            if (data.hasOwnProperty('shaman_checkout')) {
                obj['shaman_checkout'] = ApiClient.convertToType(data['shaman_checkout'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Whether the Shaman checkout directory will be removed along with the job.
 * @member {Boolean} shaman_checkout
 */
JobDeletionInfo.prototype['shaman_checkout'] = undefined;






export default JobDeletionInfo;

