/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobPriorityChange model module.
 * @module model/JobPriorityChange
 * @version 0.0.0
 */
class JobPriorityChange {
    /**
     * Constructs a new <code>JobPriorityChange</code>.
     * @alias module:model/JobPriorityChange
     * @param priority {Number} 
     */
    constructor(priority) { 
        
        JobPriorityChange.initialize(this, priority);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, priority) { 
        obj['priority'] = priority;
    }

    /**
     * Constructs a <code>JobPriorityChange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobPriorityChange} obj Optional instance to populate.
     * @return {module:model/JobPriorityChange} The populated <code>JobPriorityChange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobPriorityChange();

            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} priority
 */
JobPriorityChange.prototype['priority'] = undefined;






export default JobPriorityChange;

