/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobStatus from './JobStatus';

/**
 * The SocketIOJobUpdate model module.
 * @module model/SocketIOJobUpdate
 * @version 0.0.0
 */
class SocketIOJobUpdate {
    /**
     * Constructs a new <code>SocketIOJobUpdate</code>.
     * Subset of a Job, sent over SocketIO when a job changes. For new jobs, &#x60;previous_status&#x60; will be excluded. 
     * @alias module:model/SocketIOJobUpdate
     * @param id {String} UUID of the Job
     * @param updated {Date} Timestamp of last update
     * @param status {module:model/JobStatus} 
     * @param type {String} 
     * @param priority {Number} 
     * @param refreshTasks {Boolean} Indicates that the client should refresh all the job's tasks. This is sent for mass updates, where updating each individual task would generate too many updates to be practical. 
     */
    constructor(id, updated, status, type, priority, refreshTasks) { 
        
        SocketIOJobUpdate.initialize(this, id, updated, status, type, priority, refreshTasks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, updated, status, type, priority, refreshTasks) { 
        obj['id'] = id;
        obj['updated'] = updated;
        obj['status'] = status;
        obj['type'] = type;
        obj['priority'] = priority || 50;
        obj['refresh_tasks'] = refreshTasks;
    }

    /**
     * Constructs a <code>SocketIOJobUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SocketIOJobUpdate} obj Optional instance to populate.
     * @return {module:model/SocketIOJobUpdate} The populated <code>SocketIOJobUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SocketIOJobUpdate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = JobStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('previous_status')) {
                obj['previous_status'] = JobStatus.constructFromObject(data['previous_status']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('refresh_tasks')) {
                obj['refresh_tasks'] = ApiClient.convertToType(data['refresh_tasks'], 'Boolean');
            }
            if (data.hasOwnProperty('delete_requested_at')) {
                obj['delete_requested_at'] = ApiClient.convertToType(data['delete_requested_at'], 'Date');
            }
            if (data.hasOwnProperty('was_deleted')) {
                obj['was_deleted'] = ApiClient.convertToType(data['was_deleted'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * UUID of the Job
 * @member {String} id
 */
SocketIOJobUpdate.prototype['id'] = undefined;

/**
 * Name of the job
 * @member {String} name
 */
SocketIOJobUpdate.prototype['name'] = undefined;

/**
 * Timestamp of last update
 * @member {Date} updated
 */
SocketIOJobUpdate.prototype['updated'] = undefined;

/**
 * @member {module:model/JobStatus} status
 */
SocketIOJobUpdate.prototype['status'] = undefined;

/**
 * @member {module:model/JobStatus} previous_status
 */
SocketIOJobUpdate.prototype['previous_status'] = undefined;

/**
 * @member {String} type
 */
SocketIOJobUpdate.prototype['type'] = undefined;

/**
 * @member {Number} priority
 * @default 50
 */
SocketIOJobUpdate.prototype['priority'] = 50;

/**
 * Indicates that the client should refresh all the job's tasks. This is sent for mass updates, where updating each individual task would generate too many updates to be practical. 
 * @member {Boolean} refresh_tasks
 */
SocketIOJobUpdate.prototype['refresh_tasks'] = undefined;

/**
 * If job deletion was requested, this is the timestamp at which that request was stored on Flamenco Manager. 
 * @member {Date} delete_requested_at
 */
SocketIOJobUpdate.prototype['delete_requested_at'] = undefined;

/**
 * When a job was just deleted, this is set to `true`. If this is specified, only the 'id' field is set, the rest will be empty. 
 * @member {Boolean} was_deleted
 */
SocketIOJobUpdate.prototype['was_deleted'] = undefined;






export default SocketIOJobUpdate;

