/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkerCluster from './WorkerCluster';

/**
 * The WorkerClusterList model module.
 * @module model/WorkerClusterList
 * @version 0.0.0
 */
class WorkerClusterList {
    /**
     * Constructs a new <code>WorkerClusterList</code>.
     * @alias module:model/WorkerClusterList
     */
    constructor() { 
        
        WorkerClusterList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkerClusterList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkerClusterList} obj Optional instance to populate.
     * @return {module:model/WorkerClusterList} The populated <code>WorkerClusterList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkerClusterList();

            if (data.hasOwnProperty('clusters')) {
                obj['clusters'] = ApiClient.convertToType(data['clusters'], [WorkerCluster]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/WorkerCluster>} clusters
 */
WorkerClusterList.prototype['clusters'] = undefined;






export default WorkerClusterList;

