/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkerTag model module.
 * @module model/WorkerTag
 * @version 0.0.0
 */
class WorkerTag {
    /**
     * Constructs a new <code>WorkerTag</code>.
     * Tag of workers. A job can optionally specify which tag it should be limited to. Workers can be part of multiple tags simultaneously. 
     * @alias module:model/WorkerTag
     * @param name {String} 
     */
    constructor(name) { 
        
        WorkerTag.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>WorkerTag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkerTag} obj Optional instance to populate.
     * @return {module:model/WorkerTag} The populated <code>WorkerTag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkerTag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * UUID of the tag. Can be ommitted when creating a new tag, in which case a random UUID will be assigned. 
 * @member {String} id
 */
WorkerTag.prototype['id'] = undefined;

/**
 * @member {String} name
 */
WorkerTag.prototype['name'] = undefined;

/**
 * @member {String} description
 */
WorkerTag.prototype['description'] = undefined;






export default WorkerTag;

